[package]
name = "mnemo-package"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
age.workspace = true
ed25519-dalek.workspace = true
hex.workspace = true
mnemo-schema = { version = "0.1.0-alpha.1", path = "../mnemo-schema" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
signature.workspace = true
tar.workspace = true
thiserror.workspace = true
zstd.workspace = true

[lints]
workspace = true
