[package]
name = "mnemo-adapter-qoder"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
mnemo-adapter-common = { version = "0.1.0", path = "../common" }
mnemo-schema = { version = "0.1.0", path = "../../mnemo-schema" }

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
